# Use Microsoft's official .NET image.
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Build your application.
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/reflex.API/reflex.API/reflex.API.csproj", "reflex.API/"]
RUN dotnet restore "src/reflex.API/reflex.API/reflex.API.csproj"
COPY . .
WORKDIR "/src/MyApi"
RUN dotnet build "reflex.API.csproj" -c Release -o /app/build

# Publish the application.
FROM build AS publish
RUN dotnet publish "reflex.API.csproj" -c Release -o /app/publish

# Final stage/image.
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "reflex.API.dll"]
